default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV.fetch("DATABASE_URL") { "postgres://postgres:password@db:5432" } %>

development:
  <<: *default
  database: jobseeker_crm_development

test:
  <<: *default
  database: jobseeker_crm_test

production:
  <<: *default
  database: jobseeker_crm_production
